### ISSUE TITLE
Service stop load music file after pause

### ISSUE THREAD

**Issue by petRUShka** [tiliado/nuvola-app-yandex-music#1]
Scenario:
1. Start some track
2. Pause it
3. Resume playback 

After step #3 song will play for 20-30 seconds (I think that is the size of cache) and then will stop playback. Your only option in that case is to play next or previous song that isn't good.

**Comment by jiri-janousek** [comment]
Hello @petRUShka. Thanks for taking the time to report this issue. I apologize for a really late reply, but it seems I somehow missed an e-mail notification about this issue. Does the issue still occur?

**Comment by petRUShka** [comment]
I stopped using nuvola + yandex because of this. I will check!

**Comment by jiri-janousek** [comment]
Hello. I'm closing this issue as I haven't received any response to my request for more information I posted on December 22nd, 2015. If the issue still persists, feel free to add missing information and reopen this ticket.
