### ISSUE TITLE
Onboarding @aleksey-zhidkov

### ISSUE THREAD

**Issue by d-r-q** [tiliado/nuvola-app-yandex-music#10]

**Comment by jiri-janousek** [comment]
Hello @aleksey-zhidkov. Thanks for your interest in becoming a member of Nuvola Apps project. There are a few actions to take. You can tick them here for your convenience.

- [x] I've invited you to [Nuvola Maintainers](https://github.com/orgs/tiliado/teams/nuvola-maintainers/members) team. After you accept the invitation, you will have write access to the Yandex Music repository.
- [x] Please [create a Tiliado account](https://tiliado.eu/accounts/signup/) and tell me your username. Your account will be then upgraded to developer account and you will gain free access to [flatpak builds of Nuvola 4.x](https://nuvola.tiliado.eu) including all premium features.
- [x] Subscribe to [the nuvola-player-devel mailing list](https://groups.google.com/d/forum/nuvola-player-devel) as important announcements are posted there. This mailing list has low traffic so don't be afraid that your mailbox will be full of spam.
- [x] Take a look at [Service Integration Guidelines](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html): Rules and guidelines you should follow. Please make sure you are familiar with the [process how releases](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#releases) are made. If you have any questions about the guidelines or suggestions to improve them, don't hesitate to ask here.
- [x] Make yourself familiar with [Nuvola ADK](https://github.com/tiliado/nuvolaruntime/wiki/Nuvola-App-Developer-Kit) and try to build & run your script. If there are any issues, don't hesitate to ask here.

Ping me once you are ready for next steps.

**Comment by d-r-q** [comment]
@fenryxo I already have Tiliado account - aleksey.zhidkov

**Comment by jiri-janousek** [comment]
> I already have Tiliado account - aleksey.zhidkov

:+1: Upgraded to Tiliado developers

**Comment by d-r-q** [comment]
@fenryxo, I'm try to build script and getting this error:
```
atomic-armchair:Alive/nuvola-apps/nuvola-app-yandex-music> ./configure --with-dbus-launcher                       (master|✔)
Makefile written. Run `make all` and then `make install`.
atomic-armchair:Alive/nuvola-apps/nuvola-app-yandex-music> make all                                               (master|✔)
valac  --vapidir="/home/azhidkov/.local/lib/python3.5/site-packages/nuvolasdk/data/vapi" --pkg gio-2.0 --pkg gtk+-3.0 --pkg gio-unix-2.0 --pkg nuvolaruntime-runner -X "-DNUVOLASDK_APP_ID=\"yandex_music\"" -X "-DNUVOLASDK_UNIQUE_ID=\"eu.tiliado.NuvolaAppYandexMusic\"" -X "-DNUVOLASDK_FLATPAK_BUILD=0" -X "-DNUVOLASDK_APP_DATA_DIR=\"/usr/local/share/nuvolaruntime/web_apps/yandex_music\"" -o nuvola-app-yandex-music /home/azhidkov/.local/lib/python3.5/site-packages/nuvolasdk/data/launch_app.vala
error: Package `nuvolaruntime-runner' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
Makefile:25: recipe for target 'nuvola-app-yandex-music' failed
make: *** [nuvola-app-yandex-music] Error 1
```

And cannot understand how to fix it

**Comment by jiri-janousek** [comment]
ADK seems to be trimmed not to include Nuvola VAPI files. You can build the script without `--with-dbus-launcher` as it is unnecessary for development. It is used in regular flatpak builds.

**Comment by jiri-janousek** [comment]
tiliado/nuvolasdk#4

**Comment by jiri-janousek** [comment]
I recommend going through [Service Integration Tutorial](https://tiliado.github.io/nuvolaplayer/development/apps/tutorial.html), which provides information on how to use Nuvola SDK and to create web app scripts.

**Comment by d-r-q** [comment]
I've runned Yandex Music script, so I believe, that I'm ready for next steps

**Comment by jiri-janousek** [comment]
Great :+1:

- [x] Change `maintainer_*` in https://github.com/tiliado/nuvola-app-yandex-music/blob/master/metadata.in.json
- [x] Make sure you understand all code in `integrate.js`.
- [x] Increase `api_major` & `api_minor` to 4.8 in `metadata.json`.
- [x] Use [custom actions API](https://tiliado.github.io/nuvolaplayer/development/apps/custom-actions.html) to integrate the like button - ticket #2.
- [ ] Look at [Media Player Integration](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html) and consider adding relevant missing functionality, e.g. [track rating](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#track-rating), [progress bar](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#progress-bar) and [volume management](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#volume-management) integration.

**Comment by jiri-janousek** [comment]
> Look at [Media Player Integration](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html) and consider adding relevant missing functionality, e.g. [track rating](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#track-rating), [progress bar](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#progress-bar) and [volume management](https://tiliado.github.io/nuvolaplayer/development/apps/mediaplayer.html#volume-management) integration.

Reticketed as #12.
