### ISSUE TITLE
Provide pre-compiled downloadable releases for popular systems (Linux, Windows)

### ISSUE THREAD

**Issue by MurzNN** [tiliado/nuvola-app-yandex-music#13]
Will be good to have pre-compiled downloadable releases for popular systems - Linux (`.deb` file for Debian/Ubuntu, `.rpm` for Red Hat, etc), Windows (if supported), Mac, etc.

**Comment by jiri-janousek** [comment]
Hello @MurzNN. I provide [cross-distribution flatpak builds for Linux](https://nuvola.tiliado.eu/). Mac and Windows are not supported.

**Comment by MurzNN** [comment]
Thanks, I don't see this link in project readme and try to install it manually via `Installation` section. Please add [this link](https://nuvola.tiliado.eu/app/yandex_music/) in top of readme.md file for regular users, that wants only install and use it.

**Comment by jiri-janousek** [comment]
Good idea. Reticketed as tiliado/nuvolaruntime#407.
