### ISSUE TITLE
Shortcut for like button

### ISSUE THREAD

**Issue by ivanbalashov239** [tiliado/nuvola-app-yandex-music#2]
i want to press like for song i'm listening by pressing global shortcut

**Comment by jiri-janousek** [comment]
Hello @seniorivn. Thanks for you feature request. I might look at it in January tiliado/nuvolaplayer.project#19

**Comment by jiri-janousek** [comment]
Hello @seniorivn. If you are still interested in this feature, I would like to ask you for help: Could you create a new Yandex Music account for me with an arbitrary username and password? I cannot get through the CAPTCHA test with Russian letters.

**Comment by ivanbalashov239** [comment]
@fenryxo i don't think i'm interested, but i'll help. Check your mail for login and password.

**Comment by jiri-janousek** [comment]
Thanks :-)

**Comment by jiri-janousek** [comment]
Released in 1.5.
