### ISSUE TITLE
Shortcut for like button doesnt work

### ISSUE THREAD

**Issue by dumprop** [tiliado/nuvola-app-yandex-music#21]
![image](https://user-images.githubusercontent.com/34004367/141682664-f366e5c7-34ab-46cd-b82c-df7f9d15363e.png)
It always locked (in that state)

**Comment by jiri-janousek** [comment]
Hello @dumprop, thanks for reporting the problem.

Hello @d-r-q, is it possible to fix it?

**Comment by d-r-q** [comment]
Hi @jiri-janousek 
I will look at it at the weekend

**Comment by jiri-janousek** [comment]
The fix is available in Yandex Music 1.8.1 (1-g6e4b5d5).

**Comment by dumprop** [comment]
> The fix is available in Yandex Music 1.8.1 (1-g6e4b5d5).

Yes, thanks!
