### ISSUE TITLE
No song cover

### ISSUE THREAD

**Issue by dumprop** [tiliado/nuvola-app-yandex-music#25]
There always :no_entry_sign: 
![Screenshot from 2021-11-24 02-41-07](https://user-images.githubusercontent.com/34004367/143146089-26cb8dbc-9d60-4870-9e61-bcdf2c73aefd.png)
So, seems currently it doesn't work and fix is needed

**Comment by jiri-janousek** [comment]
Hello @dumprop, thanks for reporting the issue.

Hello @d-r-q, is it possible to fix it? Thank you.

**Comment by d-r-q** [comment]
Hello @jiri-janousek 

Initially I should post my own bug report about nuvola broken after system update (that brought Gnome 41) :)
![image](https://user-images.githubusercontent.com/1336130/143321292-096bdf4d-6a79-40c1-be62-92dc2aa36501.png)

**Comment by jiri-janousek** [comment]
There was similar problem in tiliado/nuvolaplayer#771. Installing `xdg-desktop-portal-gnome` and rebooting helped.

**Comment by d-r-q** [comment]
Yep, it has worked.
I will at this issue at the weekend

**Comment by jiri-janousek** [comment]
The fix is available in Yandex Music 1.8.2 (2-g667a918).
